name: 'PR comments based on Detekt results'
description: 'Deteklt will leave comments on pull requests.Uses Detekt 1.18.0-RC2. Forked from https://github.com/alaegin/Detekt-Action'
author: 'Alexey Egin (alaegin)'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  reviewdog_level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'error'
  reviewdog_filter:
    description: 'Filter mode for reviewdog [added,diff_context,file,nofilter]'
    required: false
    default: 'added'
  reviewdog_reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: 'github-pr-check'
  detekt_config:
    description: 'yml detekt config'
    required: false
    default: 'config/detekt/detekt.yml'
  detekt_excludes:
    description: 'Globing patterns describing paths to exclude from the analysis.'
    required: false
    default: '**/build/**,**/.idea/**'
  fail_on_error:
    description: |
      Fails the current check if any error was found [true/false]
      Default is false.
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.reviewdog_level }}
    - ${{ inputs.reviewdog_filter }}
    - ${{ inputs.reviewdog_reporter }}
    - ${{ inputs.detekt_config }}
    - ${{ inputs.detekt_excludes }}
    - ${{ inputs.fail_on_error }}
branding:
  icon: 'check-square'
  color: 'orange'
